import Link from "next/link"

import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="overflow-hidden">
      <body className={`${inter.variable} antialiased`}>
        <div className="h-20 w-full bg-zinc-900">
          <header className="absolute left-0 top-7 ml-5 mr-auto opacity-100">
            <div className="flex justify-between">
              <Link href="/">
                <p className="z-20 text-white">home</p>
              </Link>
            </div>
          </header>
        </div>
        <div className="px-5 pt-20">{children}</div>
      </body>
    </html>
  )
}
